
menu-design:
  title: "&8&LGENBUCKET MENU"
  rows: 4
  items:
    CobbleVertical:
      slot: 3
    CobbleHorizontal:
      slot: 5
  background:
    item: BLACK_STAINED_GLASS_PANE

genbuckets:
  CobbleVertical:
    material: COBBLESTONE
    bucket-item: LAVA_BUCKET
    bucket-name: "[MATERIAL] GenBucket"
    bucket-type: Vertical
    bucket-lore:
      - "-----------------------------------"
      - "Type: [TYPE]"
      - "-----------------------------------"
  CobbleHorizontal:
    material: COBBLESTONE
    bucket-item: LAVA_BUCKET
    bucket-name: "[MATERIAL] GenBucket"
    bucket-type: Horizontal
    bucket-size: 16
    bucket-lore:
      - "-----------------------------------"
      - "Type: [TYPE] ([SIZE])"
      - "-----------------------------------"