settings:
  replace-bucket: false
  max-buckets: 25000
  clear-drops: true
  click-menu: true
  tick-speed: 5

menu-design:
  title: "&a&LGENBUCKET MENU"
  rows: 4
  background: BLACK_STAINED_GLASS_PANE

genbuckets:
  CobbleVertical:
    patch: false
    material: COBBLESTONE
    menu-slot: 12
    bucket-cost: 200
    bucket-item: LAVA_BUCKET
    bucket-name: "&7&lCobblestone Vertical"
    bucket-type: Vertical
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"
  ObsidianPatch:
    patch: true
    material: OBSIDIAN
    menu-slot: 13
    bucket-cost: 250
    bucket-item: LAVA_BUCKET
    bucket-name: "&7&lObsidian Patch"
    bucket-type: Vertical
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"
  CobbleHorizontal:
    material: COBBLESTONE
    menu-slot: 14
    bucket-cost: 250
    bucket-item: LAVA_BUCKET
    bucket-name: "&7&lCobblestone Horizontal"
    bucket-type: Horizontal
    bucket-size: 16
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"
  ObsidianPrintable:
    patch: false
    material: OBSIDIAN
    menu-slot: 22
    bucket-cost: 250
    bucket-item: OBSIDIAN
    bucket-name: "&7&lObsidian Printable"
    bucket-type: Vertical
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"