genbuckets:
  CobbleVertical:
    material: COBBLESTONE
    bucket-item: LAVA_BUCKET
    bucket-name: "[MATERIAL] GenBucket"
    bucket-type: Vertical
    bucket-lore:
      - "-----------------------------------"
      - "Type: [TYPE]"
      - "-----------------------------------"
  CobbleHorizontal:
    material: COBBLESTONE
    bucket-item: LAVA_BUCKET
    bucket-name: "[MATERIAL] GenBucket"
    bucket-type: Horizontal
    bucket-size: 16
    bucket-lore:
      - "-----------------------------------"
      - "Type: [TYPE] ([SIZE])"
      - "-----------------------------------"