name: GenBuckets
main: com.reliableplugins.genbucket.GenBucket
version: ${project.version}
authors:
  - Rages
  - Driftay
softdepend:
  - Factions
  - WorldGuard
commands:
  genbucket:
    description: "The most optimized GenBucket plugin."
    usage: "/genbucket help"
    aliases: [gen, gb]